### ISSUE TITLE
Run appium tests on github-actions ci

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [aleksandr-kotlyar/appium_alfa_demo_pet_project#3]
###Todo
- [ ] Research is it possible
- [ ] Find online-emulator or docker-container
- [ ] Refactor the code to use container/external emulator
- [ ] Create github action workflows.
